[workspace]
members = [
]
[package]
name = "c2rust_out"
authors = ["C2Rust"]
version = "0.0.0"
publish = false
edition = "2018"
autobins = false

[lib]
name = "c2rust_out"
path = "c2rust-lib.rs"
crate-type = ["staticlib", "rlib"]
[[bin]]
path = "tools/dav1d.rs"
name = "dav1d"
[dependencies]
c2rust-bitfields= "0.2"
cfg-if = "1.0.0"
libc= "0.2"

[build-dependencies]
cc = "1.0.79"
nasm-rs = "0.2.4"

[features]
default = ["asm", "bitdepth_8", "bitdepth_16"]
asm = []
bitdepth_8 = []
bitdepth_16 = []
