[workspace]
members = [
]
[package]
name = "c2rust_out"
authors = ["C2Rust"]
version = "0.0.0"
publish = false
edition = "2021"
autobins = false

[lib]
name = "c2rust_out"
path = "c2rust-lib.rs"
crate-type = ["staticlib", "rlib"]
[[bin]]
path = "tools/dav1d.rs"
name = "dav1d"
[dependencies]
c2rust-bitfields= "0.3"
cfg-if = "1.0.0"
libc= "0.2"
num_cpus = "1.0"

[build-dependencies]
cc = "1.0.79"
nasm-rs = "0.2.4"

[features]
default = ["asm", "bitdepth_8", "bitdepth_16"]
asm = []
bitdepth_8 = []
bitdepth_16 = []

# `release` takes ~2min to build.
# For many use cases during iterative development,
# such as running the argon tests,
# way faster compile times is worth it for a small perf hit,
# which can be achieved with incremental compilation,
# which will bring incremental compile times down to seconds.
[profile.incr-release]
inherits = "release"
incremental = true
