[toolchain]
channel = "nightly-2024-06-13"
targets = [
    "x86_64-unknown-linux-gnu",
    "i686-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu",
    "armv7-unknown-linux-gnueabihf",
]
components = ["rustfmt"]
