name: build and benchmark on x86-64
on: [push, pull_request]
jobs:
    benchmark-on-self-hosted-x86-64:
        runs-on: [self-hosted, linux, X64]
        steps:
            - name: git checkout
              uses: actions/checkout@v3
              with:
                fetch-depth: 1
            - run: nice cargo build --release
            - name: benchmark on chimera 8-bit test data
              run: |
                mkdir -p `dirname $LOCAL_FILE`
                [ ! -f "$LOCAL_FILE" ] && curl -s -o $LOCAL_FILE $REMOTE_URL
                time target/release/dav1d -i $LOCAL_FILE -o /dev/null
              env:
                REMOTE_URL: http://download.opencontent.netflix.com.s3.amazonaws.com/AV1/Chimera/Old/Chimera-AV1-8bit-1280x720-3363kbps.ivf
                LOCAL_FILE: tests/dav1d-test-data/8-bit/chimera/Chimera-AV1-8bit-1280x720-3363kbps.ivf
            - name: benchmark on chimera 10-bit test data
              run: |
                mkdir -p `dirname $LOCAL_FILE`
                [ ! -f "$LOCAL_FILE" ] && curl -s -o $LOCAL_FILE $REMOTE_URL
                time target/release/dav1d -i $LOCAL_FILE -o /dev/null
              env:
                REMOTE_URL: http://download.opencontent.netflix.com.s3.amazonaws.com/AV1/Chimera/Old/Chimera-AV1-10bit-1920x1080-6191kbps.ivf
                LOCAL_FILE: tests/dav1d-test-data/10-bit/chimera/Chimera-AV1-10bit-1920x1080-6191kbps.ivf
