name: build and test on x86-64
on: [push, pull_request]
jobs:
  cargo-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Check formatting
        run: |
          cargo fmt --check
